networks:
  klausnet:
volumes:
  klaus-postgres-data:
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    container_name: klaus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: klaus
    volumes:
      - klaus-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -q -d klaus -U postgres"
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 40s
      start_interval: 5s
    ports:
      - "5432:5432"
    networks:
      - klausnet